apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zvwg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-zvwg@sha256:ac7103283316d054adc1f49fd9a486715a0bf0dc65bd8d4ef21e504dbed328fe
        name: my-nodejs
        resources: {}
status: {}
